name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - test  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows-based runner to build Windows container images

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login ${{ secrets.AZURE_REGISTRY_URL }} -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # Path to your project directory
        file: ./Dockerfile  # Path to your Dockerfile
        push: true  # Set to true to push to the registry
        tags: ${{ secrets.AZURE_REGISTRY_URL }}/app-service-web-dotnet-get-started:latest  # Image tag

    - name: Logout from Docker
      run: docker logout ${{ secrets.AZURE_REGISTRY_URL }}
